apiVersion: apps/v1
kind: Deployment
metadata:
  name: yanivomc-deployment
  labels:
    app: frontened
spec:
  replicas: 2
  strategy:
     type: RollingUpdate
     rollingUpdate:
        maxSurge: 25%       # how many pods we can add at a time
        maxUnavailable: 100%
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: frontened
    spec:
      containers:
      - name: yanivomc
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080
